### ISSUE TITLE
Working with lovelace

### ISSUE THREAD

**Issue by klaasnicolaas** [klaasnicolaas/Smarthome-homeassistant-config#24]
Since in Home Assistant 0.85.0 chances are that lovelace will become the new standard UI.

I started building my own lovelace panels. I have chosen to use the `yaml mode`, with the disadvantage that you can not use the Editor UI.

If anyone has nice examples of lovelace panels, please share them with me 😄

**Comment by klaasnicolaas** [comment]
See that you can't show groups in lovelace like a whole group with automations.
Now I came across this [custom group card](https://github.com/ciotlosm/custom-lovelace/tree/master/group-card), which I will try this week.

**Comment by klaasnicolaas** [comment]
Since Lovelace is now default in 0.86.2, time to pimp my lovelace UI 😄

**Comment by Holewijn** [comment]
Hey @klaasnicolaas im using ur repo as example for mine, i want to add the weather state card, https://github.com/bramkragten/custom-ui/tree/master/weather-card
Where do i put the 

resources:
- url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  type: module

i cant seem to find where to put them in because if i do them in de package (lovelace.yaml) im getting 

Package lovelace setup failed. Component resources does not exist
Component not found: resources

**Comment by klaasnicolaas** [comment]
@Holewijn funny, I'm also working on it right now 😄

**Comment by Holewijn** [comment]
Tell me when u got it working please! 👍

**Comment by klaasnicolaas** [comment]
I got it working, but I use YAML mode, a very splitted config and store the `.js` files local

**Comment by Holewijn** [comment]
Oke, i am using the easy way UI Config, because i am still learning ^^ if u could upload it, so i can have a check how u have it would be great ^^

**Comment by klaasnicolaas** [comment]
https://github.com/klaasnicolaas/Smarthome-homeassistant-config/blob/master/lovelace/resources/weather.yaml

**Comment by Holewijn** [comment]
tnx, got it working. I had to use the raw editor to add the resources
